LMS/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/author', 'AuthorController');
Route::resource('/book', 'bookController');
Route::post('/status/{id}','AuthorController@status')->name('status');
Route::post('/book_status/{id}','bookController@status')->name('book_status');

LMS/resources/views/auhtor_add.blade.php
@extends('layouts.app')

{{--    <meta charset="UTF-8">--}}
{{--    <meta name="viewport"--}}
{{--          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">--}}
{{--    <meta http-equiv="X-UA-Compatible" content="ie=edge">--}}
    <title>Registraion</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

@section('content')


<div class="container">

    <form action="{{route('author.store')}}" method="post">
        <input type="hidden" name="_token" value="{{csrf_token()}}">
        <div class="form-group">
            <label for="full_name">Full_Name:</label>
            <input type="text" class="form-control @error('full_name') is-invalid @enderror" id="full_name" name="full_name" autofocus>
            @error('full_name')
            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
            @enderror
        </div>
        <div class="form-group">
            <label for="dob">Date of Birth</label>
            <input type="date" class="form-control @error('dob') is-invalid @enderror" id="dob" name="dob">
            @error('dob')
            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
            @enderror
        </div>
{{--        <div class="form-group">--}}
{{--            <label for="gender">Gender:</label>--}}
{{--            <input type="text" class="form-control @error('gender') is-invalid @enderror" id="gender" name="gender">--}}
{{--            @error('gender')--}}
{{--            <span class="invalid-feedback" role="alert">--}}
{{--                                        <strong>{{ $message }}</strong>--}}
{{--                                    </span>--}}
{{--            @enderror--}}
{{--        </div>--}}

    <!-- Default inline 1-->
{{--        <div class = "form-group">--}}
{{--            <label for="dob">Gender:</label>--}}
{{--        <div class="custom-control custom-radio custom-control-inline">--}}
{{--            <input type="radio" class="custom-control-input" id="male" name="gender">--}}
{{--            <label class="custom-control-label" for="male">Male</label>--}}
{{--        </div>--}}

{{--        <!-- Default inline 2-->--}}
{{--        <div class="custom-control custom-radio custom-control-inline">--}}
{{--            <input type="radio" class="custom-control-input" id="female" name="gender">--}}
{{--            <label class="custom-control-label" for="female">Female</label>--}}
{{--        </div>--}}
{{--        </div>--}}
        <div class = "form-group">
            <div id="gender-group" class="form-group{{ $errors->has('gender') ? ' has-error' : '' }}">
        <label for="gender" class="col-md-4 control-label">Gender</label>

        <div class="col-md-6">
        <div><input id="female" type="radio"class="form-control" name="gender" value="Female" {{ (old('grnder') == 'female') ? 'checked' : '' }} >Female</div>
        <div><input id="male" type="radio"class="form-control" name="gender" value="Male" {{ (old('gender') == 'male') ? 'checked' : '' }} >Male</div>

        @if ($errors->has('gender'))
        <span class="help-block">
        <strong>{{ $errors->first('gender') }}</strong>
        </span>
         @endif
         </div>
        </div>
        </div>
        <div class="form-group">
            <label for="addres">Address:</label>
            <textarea class="form-control @error('address') is-invalid @enderror" rows="5" id="address" name="address"></textarea>
            @error('address')
            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
            @enderror
        </div>

        <div class="form-group">
            <label for="ph_no">Mobile:</label>
            <input type="tel" class="form-control @error('ph_no') is-invalid @enderror" id="ph_no" name="ph_no">
            @error('ph_no')
            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
            @enderror
        </div>
        <div class="form-group">
            <label for="description">description:</label>
            <textarea class="form-control @error('desciption') is-invalid @enderror" rows="5" id="description" name="description"></textarea>
            @error('description')
            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
            @enderror
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

@endsection

LMS/resources/views/author.blade.php
@extends('layouts.app')
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Show</title>
@section('content')
<div class="container">

    <table class="table">
        <thead>
        <tr>

            <th scope="col">FullName</th>
            <th scope="col">Date_of_Birth</th>
            <th scope="col">Gender</th>
            <th scope="col">Address</th>
            <th scope="col">Phone_no.</th>
            <th scope="col">Description</th>
            <th scope="col">Status</th>
            <th scope="col">Delete</th>
            <th scope="col">Edit</th>
            <th scope="col">show</th>
            <th>  <a type="btn" class="btn btn-primary" href="/author/create">add</a></th>
        </tr>
        </thead>
        <tbody>
        @foreach($data as $data)
            <tr>

                <td>{{$data->full_name}}</td>
                <td>{{$data->dob}}</td>
                <td>{{$data->gender}}</td>
                <td>{{$data->address}}</td>
                <td>{{$data->ph_no}}</td>
                <td>{{$data->description}}</td>
                <td>@if($data->status == 1)
                        <form action="{{ route('status', $data->id) }}" method="POST">
                            {{ csrf_field() }}
                            <button type="submit" class="btn btn-success" name="status" value="0">Active</button>
                        </form>
                    @else
                        <form action="{{ route('status', $data->id) }}" method="POST">
                            {{ csrf_field() }}
                            <button type="submit" class="btn btn-secondary" name="status" value="1">Inactive</button>
                        </form>
                    @endif
                </td>
                <td>
                    <form method="post" class="delete_form" action="/author/{{$data->id}}">
                        @csrf
                        <input type="hidden" name="_method" value="DELETE" />
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </td>

                <td><a type="button" class="btn btn-success" href="/author/{{$data->id}}/edit">Edit</a></td>
                <td><a type="button" class="btn btn-success" href="/author/{{$data->id}}">show</a></td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>
@endsection

LMS/resources/views/author_edit.blade.php
@extends('layouts.app')

    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Registraion</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

@section('content')

<div class="container">

    <form action={{route('author.update',$data->id)}} method="post">
{{--        <input type="hidden" name="_token" value="{{csrf_token()}}">--}}
        {{csrf_field()}}
        @method('PATCH')

        <div class="form-group">
            <label for="full_name">Full_Name:</label>
            <input type="text" class="form-control @error('full_name') is-invalid @enderror" id="full_name" name="full_name"  value="{{$data->full_name}}" autofocus>
            @error('full_name')
            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
            @enderror
        </div>
        <div class="form-group">
            <label for="dob">Date of Birth</label>
            <input type="date" class="form-control @error('dob') is-invalid @enderror" value = "{{$data->dob}}"id="dob" name="dob">
            @error('dob')
            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
            @enderror
        </div>
{{--        <div class="form-group">--}}
{{--            <label for="gender">Gender:</label>--}}
{{--            <input type="text" class="form-control @error('gender') is-invalid @enderror" id="gender"  value="{{$data->gender}}"  name="gender">--}}
{{--            @error('gender')--}}
{{--            <span class="invalid-feedback" role="alert">--}}
{{--                                        <strong>{{ $message }}</strong>--}}
{{--                                    </span>--}}
{{--            @enderror--}}
{{--        </div>--}}

{{--</div>--}}
<div class = "form-group">
    <div id="gender-group" class="form-group{{ $errors->has('gender') ? ' has-error' : '' }}">
        <label for="gender" class="col-md-4 control-label">Gender</label>

        <div class="col-md-6">
            <div><input id="female" type="radio"class="form-control" name="gender"  value="female" {{ $data->gender == 'female' ? 'checked' : ''}} >Female</div>
            <div><input id="male" type="radio"class="form-control" name="gender"  value="male" {{ $data->gender == 'male' ? 'checked' : ''}} >Male</div>

            @if ($errors->has('gender'))
                <span class="help-block">
        <strong>{{ $errors->first('gender') }}</strong>
        </span>
            @endif
        </div>
    </div>
</div>


        <div class="form-group">
            <label for="addres">Address:</label>
            <textarea class="form-control @error('address') is-invalid @enderror" rows="5" id="address"  name="address">{{$data->address}} </textarea>
            @error('address')
            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
            @enderror
        </div>

        <div class="form-group">
            <label for="ph_no">Mobile:</label>
            <input type="tel" class="form-control @error('ph_no') is-invalid @enderror" id="ph_no"   value="{{$data->ph_no}}" name="ph_no">
            @error('ph_no')
            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
            @enderror
        </div>
        <div class="form-group">
            <label for="description">description:</label>
            <textarea class="form-control @error('desciption') is-invalid @enderror" rows="5" id="description"    name="description">{{$data->description}}</textarea>
            @error('description')
            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
            @enderror
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
@endsection

LMS/resources/views/author_show.blade.php
@extends('layouts.app')
<meta charset="UTF-8">
<meta name="viewport"
      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<title>Show</title>
@section('content')
    <div class="container">

        <table class="table">

            <thead>
            <tr>

                <th scope="col">FullName</th>
                <th scope="col">Date_of_Birth</th>
                <th scope="col">Gender</th>
                <th scope="col">Address</th>
                <th scope="col">Phone_no.</th>
                <th scope="col">Description</th>
                <th scope="col">Status</th>

            </thead>
            <tbody>
            @foreach($data as $data)
                <tr>

                    <td>{{$data->full_name}}</td>
                    <td>{{$data->dob}}</td>
                    <td>{{$data->gender}}</td>
                    <td>{{$data->address}}</td>
                    <td>{{$data->ph_no}}</td>
                    <td>{{$data->description}}</td>
                    <td>@if($data->status == 1)
                            {{$data->status = 'available'}}
                        @else
                            {{$data->status = 'unavailable'}}
                        @endif
                    </td>

                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection

LMS/resources/views/book.blade.php
@extends('layouts.app')
<meta charset="UTF-8">
<meta name="viewport"
      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<title>Show</title>
@section('content')
    <div class="container">

        <table class="table">
            <thead>
            <tr>

                <th scope="col">Title</th>
                <th scope="col">Pages</th>
                <th scope="col">Language</th>
                <th scope="col">Book_Author</th>
                <th scope="col">Cover_img</th>
                <th scope="col">ISBN_code</th>
                <th scope="col">Description</th>
                <th scope="col">Status</th>
                <th scope="col">Delete</th>
                <th scope="col">Edit</th>
                <th scope="col">Show</th>
                <th>  <a type="btn" class="btn btn-primary" href="/book/create">add</a></th>
            </tr>
            </thead>
            <tbody>
            @foreach($data as $data)
                <tr>

                    <td>{{$data->title}}</td>
                    <td>{{$data->pages}}</td>
                    <td>{{$data->language}}</td>
                    <td>{{$data->book_author}}</td>
                    <td><img src="{{url('/storage/'.$data->cover_img)}}" width="100px;" height="100px;"></td>
                    <td>{{$data->ISBN_no}}</td>
                    <td>{{$data->description}}</td>
                    <td>@if($data->status == 1)
                            <form action="{{ route('book_status', $data->id) }}" method="POST">
                                {{ csrf_field() }}
                                <button type="submit" class="btn btn-success" name="status" value="0">Active</button>
                            </form>
                        @else
                            <form action="{{ route('book_status', $data->id) }}" method="POST">
                                {{ csrf_field() }}
                                <button type="submit" class="btn btn-secondary" name="status" value="1">Inactive</button>
                            </form>
                        @endif
                    </td>

                    <td>
                        <form method="post" class="delete_form" action="/book/{{$data->id}}">
                            @csrf
                            <input type="hidden" name="_method" value="DELETE" />
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </td>

                    <td><a type="button" class="btn btn-success" href="/book/{{$data->id}}/edit">Edit</a></td>
                    <td><a type="button" class="btn btn-success" href="/book/{{$data->id}}">show</a></td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection

LMS/resources/views/book_add.blade.php
@extends('layouts.app')

{{--    <meta charset="UTF-8">--}}
{{--    <meta name="viewport"--}}
{{--          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">--}}
{{--    <meta http-equiv="X-UA-Compatible" content="ie=edge">--}}
<title>Registraion</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

@section('content')


    <div class="container">

        <form action="{{route('book.store')}}" method="post" enctype="multipart/form-data">
            <input type="hidden" name="_token" value="{{csrf_token()}}">
            <div class="form-group">
                <label for="title">Title:</label>
                <input type="text" class="form-control @error('title') is-invalid @enderror" id="title" name="title" autofocus>
                @error('title')
                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                @enderror
            </div>
            <div class="form-group">
                <label for="pages">Pages</label>
                <input type="text" class="form-control @error('pages') is-invalid @enderror" id="pages" name="pages">
                @error('pages')
                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                @enderror
            </div>

            <div class="form-group">
                <label for="language">Language :</label>
                <input type="text" class="form-control @error('language') is-invalid @enderror" id="language" name="language">
                @error('language')
                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                @enderror
            </div>

            <div class="form-group">
                <label for="book_author">Book Author</label>
                <select class="custom-select @error('book_author') is-invalid @enderror" name="book_author" id="book_author">
                    <option hidden value="">Book Author</option>
                    @foreach($author as $author)
                        <option value="{{ $author->id }}">{{ $author->full_name }}</option>
                    @endforeach
                </select>
                @error('book_author')
                <span class="invalid-feedback" role="alert">
    <strong>{{ $message }}</strong>
    </span>
                @enderror
            </div>

            <div class="form-group">
                <label for="ISBN_no">Cover Image:</label>
                <input type="file" class="form-control @error('cover_img') is-invalid @enderror" id="cover_img" name="cover_img">
                @error('cover_img')
                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                @enderror
            </div>

            <div class="form-group">
                <label for="ISBN_no">ISBN Code</label>
                <input type="text" class="form-control @error('ISBN_no') is-invalid @enderror" id="ISBN_no" name="ISBN_no">
                @error('ISBN_no')
                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                @enderror
            </div>
            <div class="form-group">
                <label for="description">description:</label>
                <textarea class="form-control @error('desciption') is-invalid @enderror" rows="5" id="description" name="description"></textarea>
                @error('description')
                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                @enderror
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>

        </form>
    </div>

@endsection

LMS/resources/views/book_show.blade.php
@extends('layouts.app')
<meta charset="UTF-8">
<meta name="viewport"
      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<title>Show</title>
@section('content')
    <div class="container">

        <table class="table">
            <thead>
            <tr>

                <th scope="col">Title</th>
                <th scope="col">Pages</th>
                <th scope="col">Language</th>
                <th scope="col">Book_Author</th>
                <th scope="col">Cover_img</th>
                <th scope="col">ISBN_code</th>
                <th scope="col">Description</th>
                <th scope="col">Status</th>

            </tr>
            </thead>
            <tbody>
            @foreach($data as $data)
                <tr>

                    <td>{{$data->title}}</td>
                    <td>{{$data->pages}}</td>
                    <td>{{$data->language}}</td>
                    <td>{{$data->book_author}}</td>
                    <td><img src="{{url('/storage/'.$data->cover_img)}}" width="100px;" height="100px;"> </td>
                    <td>{{$data->ISBN_no}}</td>
                    <td>{{$data->description}}</td>
                    <td>@if($data->status == 1)
                            {{$data->status = 'available'}}
                            @else
                                {{$data->status = 'unavailable'}}
                        @endif
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection

LMS/resources/views/book_update.blade.php
@extends('layouts.app')

{{--    <meta charset="UTF-8">--}}
{{--    <meta name="viewport"--}}
{{--          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">--}}
{{--    <meta http-equiv="X-UA-Compatible" content="ie=edge">--}}
<title>Registraion</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

@section('content')


    <div class="container">

        <form action={{route('book.update',$data->id)}} method="post" enctype="multipart/form-data">
            {{--        <input type="hidden" name="_token" value="{{csrf_token()}}">--}}
            {{csrf_field()}}
            @method('PATCH')

            <div class="form-group">
                <label for="title">Title:</label>
                <input type="text" class="form-control @error('title') is-invalid @enderror" id="title" value="{{$data->title}}" name="title" autofocus>
                @error('title')
                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                @enderror
            </div>
            <div class="form-group">
                <label for="pages">Pages</label>
                <input type="text" class="form-control @error('pages') is-invalid @enderror"  value="{{$data->pages}}" id="pages" name="pages">
                @error('pages')
                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                @enderror
            </div>

            <div class="form-group">
                <label for="language">Language :</label>
                <input type="text" class="form-control @error('language') is-invalid @enderror" value="{{$data->language}}"  id="language" name="language">
                @error('language')
                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                @enderror
            </div>
            <div class="form-group">
                <label for="">Book Author</label>
                <select class="custom-select" name="book_author" id="book_author">
                    <option hidden>Book Author</option>
                    @foreach($author as $author)
                        <option value="{{ $author->id }}" {{ $data->book_author==$author->id?'selected':'' }}>{{ $author->full_name }}</option>
                    @endforeach
                </select>
            </div>

            <div class="form-group">
                <label for="ISBN_no">Cover Image:</label>
                <input type="file" class="form-control @error('cover_img') is-invalid @enderror" id="cover_img" value="{{$data->cover_img}}" name="cover_img">
                @error('cover_img')
                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                @enderror
            </div>

            <div class="form-group">
                <label for="ISBN_no">ISBN Code</label>
                <input type="text" class="form-control @error('ISBN_no') is-invalid @enderror"  value="{{$data->ISBN_no}}" id="ISBN_no" name="ISBN_no">
                @error('ISBN_no')
                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                @enderror
            </div>
            <div class="form-group">
                <label for="description">description:</label>
                <textarea class="form-control @error('desciption') is-invalid @enderror" value="" rows="5" id="description" name="description">{{$data->description}}</textarea>
                @error('description')
                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                @enderror
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>

        </form>
    </div>

@endsection